
baseURL = "https://dojomi.github.io"
languageCode = "en-us"
title = ""
theme = "minimal"

[params]
    author = "DoJoMi"
    description = "$ do | more;"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["bash" ,"go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "https://dojomi.github.io/centbox/"
    name = ">_ centbox"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dojomi/"
    name = "github"
    weight = 2

